### ISSUE TITLE
RStudio Version 1.2.1335

### ISSUE THREAD

**Issue by hhuili** [rileytwo/darkstudio#5] opened 2019-04-24 01:21 UTC
![image](https://user-images.githubusercontent.com/37439209/56625940-28e65780-6672-11e9-8dcd-3236db85a9df.png)
Hello, the color of the latest version of RStudio is still blue.

**Comment by rileytwo** [comment] 2019-05-01 12:01
Hey @hhuili thanks for making an issue. I just pushed some updates that should fix this. Can you try it out and let me know if the problem persists?

Also, can you provide me with what OS you're using and what version of RStudio you have?

**Comment by verasls** [comment] 2019-07-12 11:35
Hello you all. The same is still happening to me. 

I'm currently using RStudio Version 1.2.1335 and  macOS Mojave Version 10.14.5.

**Comment by rileytwo** [comment] 2019-07-12 11:48
@verasls, is this happening with the most recent push to this repo?

**Comment by verasls** [comment] 2019-07-12 15:29
Yes @livelaughriley. I made the push today.

**Comment by rileytwo** [comment] 2019-07-12 15:45
Can you right click and inspect the element and paste the contents in the properties, @verasls?

**Comment by verasls** [comment] 2019-07-12 19:37
Sure. Didn't know exactly what you need, so here's a screenshot:

![Screenshot 2019-07-12 at 20 35 50](https://user-images.githubusercontent.com/45968611/61153941-a9d02500-a4e4-11e9-9fbf-636a9754a71a.png)

**Comment by rileytwo** [comment] 2019-07-12 20:28
If you go to settings `Cmd+,` -> Appearance -> RStudio theme, what do you have selected? It doesn't play nice with Classic or Sky. Do you have Modern selected?

Also, what theme are you using?

I'm not able to reproduce, unfortunately, so I'll need some more info.

**Comment by verasls** [comment] 2019-07-12 21:07
Yes, I'm using Modern. But I've already tried with Sky (the console panel stayed blue) and Classic (everything goes white).

The theme I'm currently using is Idle Fingers, although I've also tried other dark themes, with the same result.

**Comment by rileytwo** [comment] 2019-07-12 21:53
I think I figured it out.

I typically have the `Jobs` tab open next to `Console`. It seems that there was a different rule for the background when only one tab is shown (in your case, `Console`).

I just pushed the edits--can you test it out for me @verasls?

**Comment by verasls** [comment] 2019-07-12 22:47
It works perfectly right now! Thanks for the attention @livelaughriley!

**Comment by rileytwo** [comment] 2019-07-12 23:24
No problem! Glad it's working for you 😄 

And hopefully @hhuili too. Closing this for now.

**Closed as completed by rileytwo** 2019-07-12 23:24 UTC
Labels: question
