### ISSUE TITLE
not working on linux. Could anyone fix it?

### ISSUE THREAD

**Issue by neosanma** [rileytwo/darkstudio#20] opened 2021-09-05 17:23 UTC

**Comment by rileytwo** [comment] 2021-09-05 19:18
Can you provide some more information? Linux distro, RStudio version, etc.

**Comment by ghost** [comment] 2021-11-08 13:46
Hi rileytwo, can confirm that neither the New or Old methods work on my GNU/Linux distro. 

Error message from R console after running `darkstudio::activate()`: Error in dirname(path) : a character vector argument expected

I did, as per the instructions, run RStudio from the terminal.

It appears that RStudio files have moved from /usr/local/rstudio to /usr/lib/rstudio and that theming/css stuff moved to /usr/lib/rstudio/resources.

Distro info from running `cat /etc/*-release`:
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

Output of `devtools::session_info()`:
─ Session info ──────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.2 (2021-11-01)
 os       Pop!_OS 20.04 LTS           
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Asia/Ho_Chi_Minh            
 date     2021-11-08                  

─ Packages ──────────────────────────────────────────────────────────────────────────
 package              * version date       lib source                              
 bit                    4.0.4   2020-08-04 [1] CRAN (R 4.1.1)                      
 bit64                  4.0.5   2020-08-30 [1] CRAN (R 4.1.1)                      
 cachem                 1.0.6   2021-08-19 [1] CRAN (R 4.1.1)                      
 callr                  3.7.0   2021-04-20 [1] CRAN (R 4.1.1)                      
 cli                    3.0.1   2021-07-17 [1] CRAN (R 4.1.1)                      
 colorspace             2.0-2   2021-06-24 [1] CRAN (R 4.1.1)                      
 crayon                 1.4.1   2021-02-08 [1] CRAN (R 4.1.1)                      
 curl                   4.3.2   2021-06-23 [1] CRAN (R 4.1.1)                      
 CVXR                 * 1.0-9   2021-01-19 [3] CRAN (R 4.0.3)                      
 darkstudio             0.2.0   2021-11-08 [1] Github (rileytwo/darkstudio@4ae188e)
 data.table           * 1.14.2  2021-09-27 [1] CRAN (R 4.1.1)                      
 desc                   1.4.0   2021-09-28 [1] CRAN (R 4.1.1)                      
 devtools               2.4.2   2021-06-07 [1] CRAN (R 4.1.1)                      
 digest                 0.6.28  2021-09-23 [1] CRAN (R 4.1.1)                      
 dplyr                * 1.0.7   2021-06-18 [1] CRAN (R 4.1.1)                      
 ellipsis               0.3.2   2021-04-29 [1] CRAN (R 4.1.1)                      
 fansi                  0.5.0   2021-05-25 [1] CRAN (R 4.1.1)                      
 fastmap                1.1.0   2021-01-25 [1] CRAN (R 4.1.1)                      
 fs                     1.5.0   2020-07-31 [1] CRAN (R 4.1.1)                      
 generics               0.1.0   2020-10-31 [1] CRAN (R 4.1.1)                      
 ggplot2                3.3.5   2021-06-25 [1] CRAN (R 4.1.1)                      
 glue                   1.4.2   2020-08-27 [1] CRAN (R 4.1.1)                      
 gmp                    0.6-2   2021-01-07 [3] CRAN (R 4.0.3)                      
 gtable                 0.3.0   2019-03-25 [1] CRAN (R 4.1.1)                      
 httr                   1.4.2   2020-07-20 [1] CRAN (R 4.1.1)                      
 jsonlite               1.7.2   2020-12-09 [1] CRAN (R 4.1.1)                      
 lattice                0.20-45 2021-09-22 [4] CRAN (R 4.1.1)                      
 lifecycle              1.0.1   2021-09-24 [1] CRAN (R 4.1.1)                      
 lubridate            * 1.8.0   2021-10-07 [1] CRAN (R 4.1.1)                      
 magrittr             * 2.0.1   2020-11-17 [1] CRAN (R 4.1.1)                      
 Matrix                 1.3-4   2021-06-01 [4] CRAN (R 4.1.0)                      
 memoise                2.0.0   2021-01-26 [1] CRAN (R 4.1.1)                      
 munsell                0.5.0   2018-06-12 [1] CRAN (R 4.1.1)                      
 pbapply                1.5-0   2021-09-16 [1] CRAN (R 4.1.1)                      
 PerformanceAnalytics * 2.0.4   2020-02-06 [1] CRAN (R 4.1.1)                      
 pillar                 1.6.3   2021-09-26 [1] CRAN (R 4.1.1)                      
 pkgbuild               1.2.0   2020-12-15 [1] CRAN (R 4.1.1)                      
 pkgconfig              2.0.3   2019-09-22 [1] CRAN (R 4.1.1)                      
 pkgload                1.2.3   2021-10-13 [1] CRAN (R 4.1.1)                      
 portfolioBacktest    * 0.3.1   2021-10-17 [1] CRAN (R 4.1.1)                      
 prettyunits            1.1.1   2020-01-24 [1] CRAN (R 4.1.1)                      
 processx               3.5.2   2021-04-30 [1] CRAN (R 4.1.1)                      
 ps                     1.6.0   2021-02-28 [1] CRAN (R 4.1.1)                      
 purrr                  0.3.4   2020-04-17 [1] CRAN (R 4.1.1)                      
 quadprog               1.5-8   2019-11-20 [1] CRAN (R 4.1.1)                      
 Quandl                 2.11.0  2021-08-11 [1] CRAN (R 4.1.1)                      
 quantmod             * 0.4.18  2020-12-09 [1] CRAN (R 4.1.1)                      
 R6                     2.5.1   2021-08-19 [1] CRAN (R 4.1.1)                      
 Rcpp                   1.0.7   2021-07-07 [1] CRAN (R 4.1.1)                      
 remotes                2.4.1   2021-09-29 [1] CRAN (R 4.1.1)                      
 rlang                  0.4.12  2021-10-18 [1] CRAN (R 4.1.1)                      
 Rmpfr                  0.8-7   2021-10-28 [3] CRAN (R 4.1.1)                      
 rprojroot              2.0.2   2020-11-15 [1] CRAN (R 4.1.1)                      
 rstudioapi             0.13    2020-11-12 [1] CRAN (R 4.1.1)                      
 rvest                * 1.0.1   2021-07-26 [1] CRAN (R 4.1.1)                      
 scales                 1.1.1   2020-05-11 [1] CRAN (R 4.1.1)                      
 sessioninfo            1.1.1   2018-11-05 [1] CRAN (R 4.1.1)                      
 testthat               3.1.0   2021-10-04 [1] CRAN (R 4.1.1)                      
 tibble                 3.1.5   2021-09-30 [1] CRAN (R 4.1.1)                      
 tidyquant            * 1.0.3   2021-03-05 [1] CRAN (R 4.1.1)                      
 tidyselect             1.1.1   2021-04-30 [1] CRAN (R 4.1.1)                      
 tseries              * 0.10-48 2020-12-04 [1] CRAN (R 4.1.1)                      
 TTR                  * 0.24.2  2020-09-01 [1] CRAN (R 4.1.1)                      
 usethis                2.0.1   2021-02-10 [1] CRAN (R 4.1.1)                      
 utf8                   1.2.2   2021-07-24 [1] CRAN (R 4.1.1)                      
 vctrs                  0.3.8   2021-04-29 [1] CRAN (R 4.1.1)                      
 withr                  2.4.2   2021-04-18 [1] CRAN (R 4.1.1)                      
 xml2                   1.3.2   2020-04-23 [1] CRAN (R 4.1.1)                      
 xts                  * 0.12.1  2020-09-09 [1] CRAN (R 4.1.1)                      
 zoo                  * 1.8-9   2021-03-09 [1] CRAN (R 4.1.1)                      

[1] /home/mark/.R/x86_64-pc-linux-gnu-library/4.1
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

**Comment by rileytwo** [comment] 2021-11-23 14:54
Duplicate of #21

**Closed as completed by rileytwo** 2021-11-23 14:54 UTC
